# Algo Matrice Transition

## Version sans commentaire
Attention ! Il faut que la matrice donnée soit constituée de nombres décimaux :  
- Si vous avez un 1 remplacez par 1.0  
- Si vous avez un 0 remplacez par 0.0  

Au sinon la fonction reverra une matrice nulle remplie de 0.  
  
Pour plus d'explication, regarder la partie testing.

In [ ]:
from numpy import *

def nombreLinks(M, j):
    count = 0
    for i in range(len(M)):
        count = count + M[j][i]
    return count;

def transitionMatrice(M, a):
    P = M
    N = len(P)
    for i in range(N):
        for j in range(N):
            if (nombreLinks(M, j) != 0):
                P[i][j] = a*M[i][j] + ((1 - a)/N)
            else:
                P[i][j] = 1/N
    return P

def pageRankMatrice(M):
    Q = M
    N = len(P)
    for i in range(N):
        for j in range(N):
            if (nombreLinks(M, j) != 0):
                Q[i][j] = Q[i][j] / nombreLinks(M, j)
            else:
                Q[i][j] = 0
    return Q

## Partie Testing

In [21]:
from numpy import *
import random as rd

def norme(X):
    norm = 0
    for i in range(len(X)):
        norm = norm + X[i]**2
    return sqrt(norm)

A = array([[0,1,1,1,1,1,0,0,0,0,0,0,0,0],
[1,0,1,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,1,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,1,0,0,0,0,0,0,0,0,0],
[1,1,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,1,1,1,0,0,0,0,0],
[1,0,0,0,0,0,0,1,0,0,0,0,0,0],
[0,0,0,0,0,1,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,1,0,1,0,0,0,0],
[0,0,0,0,0,1,0,0,0,0,1,1,1,1],
[0,0,0,0,0,0,0,0,0,1,0,1,0,0],
[0,0,0,0,0,0,0,0,0,1,0,0,1,0],
[0,0,0,0,0,0,0,0,0,1,0,0,0,1],
[0,0,0,0,0,0,0,0,0,1,1,0,0,0]])

B = array([[0.0, 0.0, 0.0, 0.0, 0.0],
    [1.0, 0.0, 0.0, 0.0, 0.0],
    [1.0, 0.0, 0.0, 0.0, 0.0],
    [1.0, 1.0, 1.0, 0.0, 0.0],
    [1.0, 1.0, 0.0, 0.0, 0.0]])

def puissance_iteree(e, M):
    Xbis = []
    for i in range(len(M)):
        Xbis.append(rd.randint(0, 100))
    while (True):
        prevXbis = Xbis
        Xbis = (M.dot(Xbis)) / norme(M.dot(Xbis))
        if (norme(Xbis - prevXbis) < e):
            break
    return norme(M.dot(Xbis)), Xbis

# Test puissance itérée sans matrice transition

print()
print("Valeur propre la plus grande de A avec ecart de 10^-2 :")
print(puissance_iteree(0.01, A)[0])
print()
print("Vecteur propre associé à la valeur propre précédente avec ecart de 10^-2 :")
print(puissance_iteree(0.01, A)[1])
print()

# Algo creation algo transi

# test nb Links
def nombreLinks(M, j):
    count = 0
    for i in range(len(M)):
        count = count + M[j][i]
    return count;

print()
print("Test nb Links B pour j = 0, Valeur attendue : 0")
print(nombreLinks(B, 0))
print("Test nb Links B pour j = 1, Valeur attendue : 1")
print(nombreLinks(B, 1))
print("Test nb Links B pour j = 2, Valeur attendue : 1")
print(nombreLinks(B, 2))
print("Test nb Links B pour j = 3, Valeur attendue : 3")
print(nombreLinks(B, 3))
print("Test nb Links B pour j = 4, Valeur attendue : 2")
print(nombreLinks(B, 4))
print()


def transitionMatrice(M, a):
    P = M
    #print(P)
    N = len(P)
    #print(N)
    for i in range(N):
        for j in range(N):
            if (nombreLinks(M, j) != 0):
                P[i][j] = a*M[i][j] + ((1 - a)/N)
                #print(a*M[i][j] + ((1 - a)/N))
            else:
                P[i][j] = 1/N
                #print(1/N)
            #print("P[", i, "][", j, "] = ", P[i][j])
    return P

C = transitionMatrice(B, 0.85)
print(C)

print()
print("Valeur propre la plus grande de C avec ecart de 10^-2 :")
print(puissance_iteree(0.00001, C)[0])
print()
print("Vecteur propre associé à la valeur propre précédente avec ecart de 10^-2 :")
print(puissance_iteree(0.00001, C)[1])
print(norme(puissance_iteree(0.00001, C)[1]))
print(C.dot(puissance_iteree(0.00001, C)[1]))
print(norme(C.dot(puissance_iteree(0.00001, C)[1])))
print()




Valeur propre la plus grande de A avec ecart de 10^-2 :
2.7040784998023613

Vecteur propre associé à la valeur propre précédente avec ecart de 10^-2 :
[0.38745572 0.22496534 0.22500057 0.22495873 0.22491909 0.15957673
 0.16583788 0.05940935 0.20037441 0.48057353 0.28283748 0.28272736
 0.28277361 0.28276921]


Test nb Links B pour j = 0, Valeur attendue : 0
0.0
Test nb Links B pour j = 1, Valeur attendue : 1
1.0
Test nb Links B pour j = 2, Valeur attendue : 1
1.0
Test nb Links B pour j = 3, Valeur attendue : 3
3.0
Test nb Links B pour j = 4, Valeur attendue : 2
2.0

[[0.2  0.03 0.03 0.03 0.03]
 [0.88 0.03 0.03 0.03 0.03]
 [0.88 0.03 0.03 0.03 0.03]
 [0.88 0.88 0.88 0.03 0.03]
 [0.88 0.88 0.03 0.03 0.03]]

Valeur propre la plus grande de C avec ecart de 10^-2 :
0.6710991462148369

Vecteur propre associé à la valeur propre précédente avec ecart de 10^-2 :
[0.11143674 0.2243521  0.2243521  0.79267234 0.50851222]
0.9999999999999999
[0.07478388 0.15056027 0.15056027 0.53196012 0.3412602 ]
0