In [ ]:
#Partie 1 :
[[0,1,1,1,1,1,0,0,0,0,0,0,0,0],
[1,0,1,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,1,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,1,0,0,0,0,0,0,0,0,0],
[1,1,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,1,1,1,0,0,0,0,0],
[1,0,0,0,0,0,0,1,0,0,0,0,0,0],
[0,0,0,0,0,1,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,1,0,1,0,0,0,0],
[0,0,0,0,0,1,0,0,0,0,1,1,1,1],
[0,0,0,0,0,0,0,0,0,1,0,1,0,0],
[0,0,0,0,0,0,0,0,0,1,0,0,1,0],
[0,0,0,0,0,0,0,0,0,1,0,0,0,1],
[0,0,0,0,0,0,0,0,0,1,1,0,0,0]]

#Partie 2 :

[[0,0,0,0,0],
[1,0,0,0,0],
[1,0,0,0,0],
[1,1,1,0,0],
[1,1,0,0,0]]

In [18]:
#Partie 4, matrices de sites

#I - Allocine (Profondeur : 25) :

Allocine = [[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
            [1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1],
            [1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0],
            [1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0]]



#II - Doc Python (Profondeur : 10) :

DocPython = [[0,0,0,0,0,0,0,0,0,0],
             [1,1,1,1,1,0,0,0,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0]]



#III - GitHub (Profondeur : 20) :

Github = [[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0],
          [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]]

In [9]:
#Partie 4, matrice de ville (Gare du Nord, Paris) :

import numpy as np
GareDuNord = np.load("Gare_du_nord_Paris_France_Matrice.npy")
print ("Gare du Nord, Paris\n",GareDuNord,"\n\n\n")

#Partie 4, matrice de ville (413 avenue Gaston Berger, Aix en Provence) :

GastonBerger = np.load("Gaston_Berger.npy")
print ("413 avenue Gaston Berger, Aix en Provence\n",GastonBerger)

Gare du Nord, Paris
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 



413 avenue Gaston Berger, Aix en Provence
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [25]:
from numpy import *
import random as rd

def norme(X):
    norm = 0
    for i in range(len(X)):
        norm = norm + X[i]**2
    return sqrt(norm)

def puissance_iteree(e, M):
    Xbis = []
    for i in range(len(M)):
        Xbis.append(rd.randint(0, 100))
    #print(Xbis)
    #count = 0
    while (True):
        #count = count + 1
        prevXbis = Xbis
        M = np.array(M)
        Xbis = (M.dot(Xbis)) / norme(M.dot(Xbis))
        
        #print("Count: ", count, ", \nXbis = ", Xbis, ", \nprevXbis = ", prevXbis)
        
        #if (count%50 == 0):
            #print("Count : ", count, ", Ecart : ", norme(Xbis - prevXbis))
        
        if (norme(Xbis - prevXbis) < e):
            #print(count)
            #print(norme(Xbis - prevXbis))
            break
    return norme(M.dot(Xbis)), Xbis

print("Allocine : \n\n",puissance_iteree(0.85,Allocine),"\n\n")
print("Analyse & Interprétation\n\n\n____________________________________________________________")

print("Doc Python : \n\n",puissance_iteree(0.85,DocPython),"\n\n")
print("Analyse & Interprétation\n\n\n____________________________________________________________")

print("GitHub : \n\n",puissance_iteree(0.85,Github),"\n\n")
print("Analyse & Interprétation\n\n\n____________________________________________________________")


print("Gare du Nord, Paris : \n\n",puissance_iteree(0.85,GareDuNord),"\n\n")
print("Analyse & Interprétation\n\n\n____________________________________________________________")

print("413 avenue Gaston Berger, Aix en Provence : \n\n",puissance_iteree(0.85,GastonBerger),"\n\n")
print("Analyse & Interprétation\n\n\n")

Allocine : 

 (5.637051989949871, array([0.73387946, 0.07583083, 0.07606801, 0.04976331, 0.04976331,
       0.49476546, 0.12738372, 0.0766286 , 0.07563678, 0.0766286 ,
       0.0766286 , 0.10631841, 0.10586562, 0.0766286 , 0.07751261,
       0.04976331, 0.13939333, 0.14693976, 0.12307148, 0.04976331,
       0.12117409, 0.15073453, 0.0766286 , 0.04976331, 0.1389621 ])) 


Analyse & Interprétation


____________________________________________________________
Doc Python : 

 (6.552689830490839, array([0.        , 0.1943493 , 0.34681197, 0.34681197, 0.34681197,
       0.34681197, 0.34681197, 0.34681197, 0.34681197, 0.34681197])) 


Analyse & Interprétation


____________________________________________________________
GitHub : 

 (18.896558804033926, array([0.20656491, 0.01228822, 0.23060066, 0.23060066, 0.23060066,
       0.23060066, 0.23060066, 0.23060066, 0.23060066, 0.23060066,
       0.23060066, 0.23060066, 0.23060066, 0.23060066, 0.23060066,
       0.23060066, 0.23060066, 0.23060066