In [ ]:
#Partie 1 :
[[0,1,1,1,1,1,0,0,0,0,0,0,0,0],
[1,0,1,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,1,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,1,0,0,0,0,0,0,0,0,0],
[1,1,0,0,0,0,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,1,1,1,0,0,0,0,0],
[1,0,0,0,0,0,0,1,0,0,0,0,0,0],
[0,0,0,0,0,1,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,1,0,1,0,0,0,0],
[0,0,0,0,0,1,0,0,0,0,1,1,1,1],
[0,0,0,0,0,0,0,0,0,1,0,1,0,0],
[0,0,0,0,0,0,0,0,0,1,0,0,1,0],
[0,0,0,0,0,0,0,0,0,1,0,0,0,1],
[0,0,0,0,0,0,0,0,0,1,1,0,0,0]]

#Partie 2 :

[[0,0,0,0,0],
[1,0,0,0,0],
[1,0,0,0,0],
[1,1,1,0,0],
[1,1,0,0,0]]

In [9]:
#Partie 4, matrices de sites

#I - Allocine (Profondeur : 25) :

[[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[1,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1],
[1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1],
[1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0],
[1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0]]



#II - Doc Python (Profondeur : 10) :

[[0,0,0,0,0,0,0,0,0,0],
[1,1,1,1,1,0,0,0,0,0],
[1,1,1,1,1,1,1,1,0,0],
[1,1,1,1,1,1,1,1,0,0],
[1,1,1,1,1,1,1,1,0,0],
[1,1,1,1,1,1,1,1,0,0],
[1,1,1,1,1,1,1,1,0,0],
[1,1,1,1,1,1,1,1,0,0],
[1,1,1,1,1,1,1,1,0,0],
[1,1,1,1,1,1,1,1,0,0]]



#III - GitHub (Profondeur : 20) :

[[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0],
[1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
[1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]]


In [9]:
#Partie 4, matrice de ville (Gare du Nord, Paris) :

import numpy as np
GareDuNord = np.load("Gare_du_nord_Paris_France_Matrice.npy")
print ("Gare du Nord, Paris\n",GareDuNord,"\n\n\n")

#Partie 4, matrice de ville (413 avenue Gaston Berger, Aix en Provence) :

GastonBerger = np.load("Gaston_Berger.npy")
print ("413 avenue Gaston Berger, Aix en Provence\n",GastonBerger)

Gare du Nord, Paris
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 1. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]] 



413 avenue Gaston Berger, Aix en Provence
 [[0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 ...
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]
 [0. 0. 0. ... 0. 0. 0.]]


In [16]:
Allocine = [[0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
            [1,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,1,1,0,0,0,0,0,0,0,1,0,0,1,0,1,1,1,1,1,1,1,1,1,1],
            [1,0,0,1,1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,1,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,1,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,1],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,1,0,0,0,0,1,0],
            [1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,1,0,0,0,0,0,0,0,1,0,0,1,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
            [1,0,0,0,0,1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,1,0,0,0]]

DocPython = [[0,0,0,0,0,0,0,0,0,0],
             [1,1,1,1,1,0,0,0,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0],
             [1,1,1,1,1,1,1,1,0,0]]

Github = [[1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,0,0],
          [1,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0,0],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1],
          [1,0,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1,1]]



from numpy import *
import random as rd

def norme(X):
    norm = 0
    for i in range(len(X)):
        norm = norm + X[i]**2
    return sqrt(norm)

def puissance_iteree(e, M):
    Xbis = []
    for i in range(len(M)):
        Xbis.append(rd.randint(0, 100))
    #print(Xbis)
    #count = 0
    while (True):
        #count = count + 1
        prevXbis = Xbis
        M = np.array(M)
        Xbis = (M.dot(Xbis)) / norme(M.dot(Xbis))
        
        #print("Count: ", count, ", \nXbis = ", Xbis, ", \nprevXbis = ", prevXbis)
        
        #if (count%50 == 0):
            #print("Count : ", count, ", Ecart : ", norme(Xbis - prevXbis))
        
        if (norme(Xbis - prevXbis) < e):
            #print(count)
            #print(norme(Xbis - prevXbis))
            break
    return norme(M.dot(Xbis)), Xbis

print("Allocine : \n\n",puissance_iteree(0.85,Allocine),"\n\n\n")
print("Doc Python : \n\n",puissance_iteree(0.85,DocPython),"\n\n\n")
print("GitHub : \n\n",puissance_iteree(0.85,Github),"\n\n\n")

print("Gare du Nord, Paris : \n\n",puissance_iteree(0.85,GareDuNord),"\n\n\n")
print("413 avenue Gaston Berger, Aix en Provence : \n\n",puissance_iteree(0.85,GastonBerger),"\n\n\n")

Allocine : 

 (6.178970006699371, array([0.45576371, 0.14943628, 0.14062598, 0.13147682, 0.13147682,
       0.36461097, 0.16208697, 0.14401456, 0.14378865, 0.14401456,
       0.14401456, 0.16604031, 0.16457193, 0.14401456, 0.14649951,
       0.13147682, 0.18558111, 0.17609309, 0.2418315 , 0.13147682,
       0.23200463, 0.25380448, 0.14401456, 0.13147682, 0.24872161])) 



Doc Python : 

 (6.548099509259285, array([0.        , 0.19175217, 0.34699263, 0.34699263, 0.34699263,
       0.34699263, 0.34699263, 0.34699263, 0.34699263, 0.34699263])) 



GitHub : 

 (18.896860563380386, array([0.20717853, 0.01193269, 0.23057111, 0.23057111, 0.23057111,
       0.23057111, 0.23057111, 0.23057111, 0.23057111, 0.23057111,
       0.23057111, 0.23057111, 0.23057111, 0.23057111, 0.23057111,
       0.23057111, 0.23057111, 0.23057111, 0.23057111, 0.23057111])) 



Gare du Nord, Paris : 

 (2.17188048630612, array([0.01983198, 0.04707372, 0.00424971, ..., 0.00871735, 0.00937116,
       0.01558227])) 



4