# Partie 1 : PageRank - version itérative, premier exemple

## Question 1

Voici l'algorithme de la puissance itérée :

In [33]:
from numpy import *
import random as rd

def norme(X):
    norm = 0
    for i in range(len(X)):
        norm = norm + X[i]**2
    return sqrt(norm)

def puissance_iteree(e, M):
    Xbis = []
    for i in range(len(M)):
        Xbis.append(rd.randint(0, 100))
    Xbis = array(Xbis)
    while (True):
        prevXbis = Xbis
        Xbis = (M.dot(Xbis)) / norme(M.dot(Xbis))
        if (norme(Xbis - prevXbis) < e):
            break
    return norme(M.dot(Xbis)), Xbis

L'algorithme de la puissance itérée permet de calculer la valeur propre la plus grande et le vecteur propre associé d'une matrice "M".  
Ce vecteur propre "v" a la particularité d'être solution de l'équation :  
    v = M v  
  
Or en regardant le principe de l'algorithme de PageRank et son explication en notations matricielles, on remarque que le principe est le même :  
Le vecteur r des scores est solution de l'équation r = Q r  où Q est la matrice d'adjacence des scores.  

## Question 2

In [34]:
A = array([[0.0,1.0,1.0,1.0,1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
[1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
[1.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
[1.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
[1.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],
[0,0,0,0,0,0,1,1,1,0,0,0,0,0],
[1,0,0,0,0,0,0,1,0,0,0,0,0,0],
[0,0,0,0,0,1,0,0,0,0,0,0,0,0],
[0,0,0,0,0,0,0,1,0,1,0,0,0,0],
[0,0,0,0,0,1,0,0,0,0,1,1,1,1],
[0,0,0,0,0,0,0,0,0,1,0,1,0,0],
[0,0,0,0,0,0,0,0,0,1,0,0,1,0],
[0,0,0,0,0,0,0,0,0,1,0,0,0,1],
[0,0,0,0,0,0,0,0,0,1,1,0,0,0]])

print("Vecteur de scores trouvé :")
print(puissance_iteree(10**-5, A)[1])

Vecteur de scores trouvé :
[0.43654207 0.25606157 0.25606157 0.25606157 0.25606157 0.15652791
 0.18278784 0.05786914 0.182729   0.43639134 0.25596504 0.25596504
 0.25596504 0.25596504]


Vérification du vecteur des scores :

In [48]:
l,r = puissance_iteree(10**-5, A)
print(l)
print("Valeur de r :")
print(r)
print()
print("Valeur de Ar :")
print(A.dot(r))

print("Valeur de Ar - r :")
print(A.dot(r) - 2.7*r)

print("Solution AX = r")
X = np.linalg.solve(A,r)
print(X)
print("On vérifie AX - r = ", A.dot(r)-r)

2.7048594833354924
Valeur de r :
[0.43653877 0.25605945 0.25605945 0.25605945 0.25605945 0.15652791
 0.18278655 0.05786914 0.18273029 0.43639465 0.25596716 0.25596716
 0.25596716 0.25596716]

Valeur de Ar :
[1.18076571 0.69259822 0.69259822 0.69259822 0.69259822 0.42338599
 0.49440791 0.15652791 0.49426379 1.18039653 0.6923618  0.6923618
 0.6923618  0.6923618 ]
Valeur de Ar - r :
[0.00211103 0.0012377  0.0012377  0.0012377  0.0012377  0.00076065
 0.00088422 0.00028121 0.00089201 0.00213098 0.00125048 0.00125048
 0.00125048 0.00125048]
Solution AX = r


LinAlgError: Singular matrix

En tentant de faire la vérification numérique avec linalg.solve(A, r), la fonction renvoie une erreur LinAlgError de type Singular matrix.  
  
Nous avons donc réalisé la vérification manuellement en faisant la soustraction entre Ar et r.  
Le résultat obtenu n'est pas celui attendu et la source de ce problème nous est inconnue.  
  
Il semblerait cependant que la hiérarchie des scores est malgrès tout correcte avec les pages 1 et 10 ayant les plus grands scores.

# Partie 2 : PageRank - version itérative, deuxième example
## Question 1

In [42]:
B = array([[0.0,0.0,0.0,0.0,0.0],
[1.0,0.0,0.0,0.0,0.0],
[1.0,0.0,0.0,0.0,0.0],
[1.0,1.0,1.0,0.0,0.0],
[1.0,1.0,0.0,0.0,0.0]])

print("Resultat des scores : ")
print(puissance_iteree(10**-5, B)[1])

Resultat des scores : 


/tmp/ipykernel_4041/3589164236.py:17: RuntimeWarning: invalid value encountered in true_divide
  Xbis = (M.dot(Xbis)) / norme(M.dot(Xbis))


KeyboardInterrupt: 

En appliquant l'algorithme de la partie 1, on se retrouve avec une erreur. Il est donc probable que la matrice d'adjacence B ne puisse par être traitée par un algorithme de puissance itérée.  
  
On va définir un algorithme qui renvoie une matrice de transition pour palier à ce problème :  

In [43]:
def nombreLinks(M, j):
    count = 0
    for i in range(len(M)):
        count = count + M[j][i]
    return count;

def transitionMatrice(M, a):
    P = M
    N = len(P)
    for i in range(N):
        for j in range(N):
            if (nombreLinks(M, j) != 0):
                P[i][j] = a*M[i][j] + ((1 - a)/N)
            else:
                P[i][j] = 1/N
    return P


## Question 2


In [44]:
T = transitionMatrice(B, 0.85)

print("Matrice de transition pour B :")
print(T)
print()
print("Vecteur score de la matrice transition :")
r2 = puissance_iteree(10**-5, T)[1]
print(r2)

print("Solution equation TX = r2 :")
X = linalg.solve(T, r2)
print(X)

print("Verification TX - r2 = :")
print(T.dot(r2) - r2)

Matrice de transition pour B :
[[0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]
 [0 0 0 0 0]]

Vecteur score de la matrice transition :


/tmp/ipykernel_4041/3589164236.py:17: RuntimeWarning: invalid value encountered in true_divide
  Xbis = (M.dot(Xbis)) / norme(M.dot(Xbis))


KeyboardInterrupt: 